//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSales
{
    using System;
    
    public partial class HizliUrun
    {
        public int HizliUrunId { get; set; }
        public string Barkod { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> Fiyat { get; set; }
    }
}