//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeSales
{
    using System;
    
    public partial class Terazi
    {
        public int TeraziId { get; set; }
        public Nullable<int> TeraziOnEk { get; set; }
    }
}